using System.Text.Json;

namespace NetLock_RMM_Web_Console.Classes.Miscellaneous
{
    public class FunFacts
    {
        public class FunFactRoot
        {
            public List<string> IT_Fun_Facts { get; set; }
        }

        public static string funFacts = """
            {
              "IT_Fun_Facts": [
                "The first computer virus was called 'Creeper' and appeared in 1971 on ARPANET.",
                "The first emoji was invented in Japan in 1999.",
                "For years, the password for the US nuclear missile control computers was just '00000000'.",
                "The first spam email was sent in 1978 to 393 recipients.",
                "Bill Gates once said in 1981 that 640 KB of RAM should be enough for anyone.",
                "The domain 'symbolics.com' is the oldest still existing domain (registered in 1985).",
                "NASA once emailed a software update to a space probe in 2013.",
                "The first webcam monitored a coffee pot at Cambridge University.",
                "CAPTCHA stands for 'Completely Automated Public Turing test to tell Computers and Humans Apart'.",
                "Over 90% of the world’s currency exists only in digital form.",
                "The Internet is estimated to weigh about as much as a strawberry.",
                "Nintendo started as a playing card company in 1889.",
                "The first computer mouse prototype was made of wood.",
                "A 5 MB IBM hard drive in 1956 weighed over one ton.",
                "The QWERTY keyboard layout was designed to prevent typewriter jams.",
                "Over 500,000 new malware variants are created every day.",
                "A single Google search requires more computing power than all of NASA had in 1969.",
                "The @ symbol has existed since the Middle Ages.",
                "The first iPhone had less processing power than today’s cheapest calculators.",
                "Around 90% of all emails sent are spam.",
                "The first computer bug was an actual moth found inside a computer.",
                "YouTube originally started as a dating site.",
                "Facebook was originally only for Harvard students.",
                "The first domain with an umlaut was 'münchen.de'.",
                "Wikipedia is visited by over 500 million people per month.",
                "The first SMS ever sent in 1992 said 'Merry Christmas'.",
                "In South Korea, professional Starcraft players have fan clubs.",
                "In 1997, IBM’s Deep Blue defeated chess world champion Garry Kasparov.",
                "95% of the world’s ATMs still ran on Windows XP for years.",
                "Java’s original name was Oak.",
                "Python was named after the comedy group 'Monty Python'.",
                "Microsoft bought MS-DOS for just $75,000.",
                "The longest password ever used had more than 1,000 characters.",
                "The first computer programs were written by Ada Lovelace in the 19th century.",
                "Google’s original name was 'BackRub'.",
                "The first computers were as big as entire rooms.",
                "In Italy, the @ sign is called 'chiocciola' (snail).",
                "The most common passwords in the world are still '123456' and 'password'.",
                "Amazon started as an online bookstore.",
                "The first version of Windows was released in 1985.",
                "In 1999, a NASA spacecraft crashed due to confusion between metric and imperial systems.",
                "The first email was sent by Ray Tomlinson in 1971.",
                "Bill Gates once famously demonstrated the Windows Blue Screen of Death on stage.",
                "More people own a mobile phone than a toothbrush.",
                "Minecraft was originally called 'Cave Game'.",
                "A 1 GB memory chip in the 1980s would have cost over $1 million.",
                "Half of all Internet traffic comes from bots.",
                "One of the first computer games was Tic-Tac-Toe played on an oscilloscope.",
                "Tesla cars can receive new features via software updates, like smartphones.",
                "The Internet was originally developed for the military.",
                "The first 1 TB hard drive was released in 2007.",
                "The first search engine was 'Archie' in 1990.",
                "A single Google server crashes only about once a year on average.",
                "A byte was once commonly called an 'octet'.",
                "The first commercial video game was Pong.",
                "The first computer programmer in history was a woman: Ada Lovelace.",
                "Linux powers over 90% of the world’s supercomputers.",
                "Windows 95 launched with a Rolling Stones song in its commercial.",
                "Over 300 billion emails are sent every day.",
                "The first IBM hard disk had just 5 MB of storage.",
                "One petabyte equals about 13.3 years of HD video.",
                "The first Wi-Fi was called 'WaveLAN'.",
                "90% of the world’s data was created in the last two years.",
                "Elon Musk founded an online bank called X.com in 1999.",
                "The first social network was SixDegrees.com in 1997.",
                "A single Bitcoin block consumes as much energy as a US household uses in a week.",
                "Apple was close to bankruptcy in 1997 before Microsoft invested.",
                "The first version of MacOS was called System 1.",
                "The name 'Wi-Fi' doesn’t actually mean anything – it was a marketing creation.",
                "Half of all IT projects fail on time or budget.",
                "The game Tetris was invented in the Soviet Union in 1984.",
                "The first Google Doodle was a Burning Man logo.",
                "HP was founded in a garage, just like many other tech giants.",
                "More than 80% of online accounts use weak passwords.",
                "A hacker attack occurs every 39 seconds on average.",
                "The first high-level programming language was Fortran.",
                "Donald Knuth sends $2.56 checks to anyone who finds an error in his books.",
                "The name 'Bluetooth' comes from a Viking king, Harald Bluetooth.",
                "The first photo on the Internet was of a comedy band called 'Les Horribles Cernettes'.",
                "The Summit supercomputer can perform 200 quadrillion calculations per second.",
                "Steve Jobs sold his Volkswagen van to fund Apple.",
                "A 1 TB text file would contain about 50 billion pages.",
                "Most banks still rely on COBOL programs.",
                "Wikipedia is maintained by only a few hundred active editors.",
                "The first Google search ever was for 'Gerhard Kasparov'.",
                "Mark Zuckerberg is red-green colorblind – that’s why Facebook is blue.",
                "Windows was originally called 'Interface Manager'.",
                "Over 95% of ATMs worldwide still run on Windows.",
                "The first computers didn’t have screens – they used punch cards.",
                "The first Apple computer was sold for $666.66.",
                "Many airplanes still use floppy disks for software updates.",
                "The Y2K bug caused worldwide panic in 1999.",
                "Google Maps originally only used satellite images from third parties.",
                "NASA still uses some code from the 1960s today.",
                "On average, a USB plug takes three tries before being inserted correctly.",
                "More than half of all Internet traffic is video streaming.",
                "The original iPod had a hidden Tetris game.",
                "In 2010, Syria’s entire Internet went offline for one hour.",
                "Over 8% of all Bitcoin is permanently lost.",
                "In 2019, NASA found tapes from the 1960s but no machine to play them.",
                "Bananas are berries, but strawberries are not.",
                "Sharks existed before trees.",
                "Octopuses have three hearts.",
                "Sloths can hold their breath longer than dolphins.",
                "Wombat poop is cube-shaped.",
                "There are more stars in the universe than grains of sand on Earth.",
                "A day on Venus is longer than a year on Venus.",
                "Some turtles can breathe through their butts.",
                "Cows have best friends and get stressed when separated.",
                "Koalas have fingerprints almost identical to humans.",
                "The heart of a blue whale is the size of a small car.",
                "Honey never spoils; edible honey was found in ancient Egyptian tombs.",
                "Your stomach gets a new lining every 3–4 days.",
                "Otters hold hands while they sleep so they don’t drift apart.",
                "Pineapples take up to two years to grow.",
                "The fingerprints of a koala are so similar to a human’s they can confuse forensic experts.",
                "Butterflies can taste with their feet.",
                "Your body has more bacteria than human cells.",
                "Sharks do not have bones; their skeletons are made of cartilage.",
                "Elephants are the only animals that cannot jump.",
                "Caterpillars completely liquefy before turning into butterflies.",
                "Every snowflake has a unique shape.",
                "Cats can’t taste sweetness.",
                "Your fingernails grow faster on your dominant hand.",
                "The Eiffel Tower can be 15 cm taller in summer due to heat expansion.",
                "Sea otters have the thickest fur in the animal kingdom.",
                "There’s enough DNA in your body to stretch from the sun to Pluto and back.",
                "Jellyfish have been around for more than 500 million years.",
                "A newborn baby has about 300 bones, but adults have 206.",
                "Avocados are technically berries.",
                "An octopus can regrow a lost arm.",
                "Butterflies remember being caterpillars.",
                "The average person walks the equivalent of five times around the world in their lifetime.",
                "Bees can recognize human faces.",
                "Otters have a special pocket to store their favorite rock.",
                "Your taste buds have a lifespan of about 10–14 days.",
                "Sloths can turn their heads almost 270 degrees.",
                "A shrimp’s heart is in its head.",
                "An ostrich’s eye is bigger than its brain.",
                "Cats have 32 muscles in each ear.",
                "A group of flamingos is called a 'flamboyance'.",
                "It takes about 8 minutes for sunlight to reach Earth.",
                "Dolphins call each other by unique names.",
                "Sharks existed before Saturn had rings.",
                "A giraffe’s tongue is about 45 cm long.",
                "Snails can sleep for up to three years.",
                "Horses can’t vomit.",
                "The human nose can detect over a trillion scents.",
                "There are more trees on Earth than stars in the Milky Way.",
                "Penguins propose to their mates with a pebble.",
                "Your heart beats about 100,000 times a day.",
                "Rats laugh when tickled.",
                "An octopus has nine brains.",
                "Your skin is your body’s largest organ.",
                "The longest hiccuping spree lasted 68 years.",
                "You are taller in the morning than in the evening.",
                "Kangaroos can’t walk backwards.",
                "Bees sometimes sting other bees.",
                "Sharks can detect a drop of blood in 25 gallons of water.",
                "Some frogs can survive being frozen solid and thaw back to life.",
                "A day on Mercury lasts 59 Earth days.",
                "Your eyes blink about 20 times per minute.",
                "Sea lions can clap underwater.",
                "Crows can hold grudges against specific people.",
                "The tongue is made up of eight muscles.",
                "Your hair grows about 1 cm per month.",
                "Some lizards can squirt blood from their eyes.",
                "Rabbits can see behind them without turning their heads.",
                "The moon is slowly moving away from Earth.",
                "The human brain has about 86 billion neurons.",
                "Polar bears have black skin under their white fur.",
                "Starfish can regrow lost arms.",
                "The average person spends about 6 months of their life waiting at red lights.",
                "Koalas sleep up to 22 hours a day.",
                "Your bones are about 5 times stronger than steel of the same density.",
                "The fingerprints of identical twins are different.",
                "Humans share about 60% of their DNA with bananas.",
                "Some fish can change sex.",
                "Owls can’t move their eyes.",
                "Sharks never stop moving, or they suffocate.",
                "Your stomach acid can dissolve razor blades.",
                "Birds are dinosaurs’ closest living relatives.",
                "The longest living animal is the Greenland shark, which can live up to 500 years.",
                "The smell of freshly cut grass is actually a plant distress signal.",
                "Your small intestine is about 6 meters long.",
                "Butterflies can remember human faces.",
                "A newborn baby can recognize its mother’s voice at birth.",
                "Pandas spend up to 14 hours a day eating.",
                "Your liver can regenerate itself completely.",
                "Some turtles can live over 200 years.",
                "A blue whale’s tongue weighs as much as an elephant.",
                "Cats sleep for about 70% of their lives.",
                "There are more bacteria in your mouth than people on Earth.",
                "You produce about 1 liter of saliva every day.",
                "Ants never sleep.",
                "Owls can rotate their heads up to 270 degrees.",
                "Your sense of smell is stronger in spring and summer.",
                "Dogs can smell 100,000 times better than humans.",
                "A day on Jupiter is only about 10 hours long.",
                "Your brain uses about 20% of your body’s total energy.",
                           "The term 'open source' was officially coined in 1998.",
            "Linux, one of the most famous open-source projects, powers most of the world’s servers.",
            "The first open-source license was created in the late 1980s.",
            "Git, the version control system, was created by Linus Torvalds in 2005.",
            "Android, the most widely used mobile OS, is based on open source.",
            "The Apache HTTP Server has been one of the most popular web servers since 1995.",
            "Mozilla Firefox started as an open-source alternative to Internet Explorer.",
            "OpenOffice later gave rise to LibreOffice, a widely used free office suite.",
            "MySQL, an open-source database, powers millions of websites worldwide.",
            "Open source powers over 90% of supercomputers.",
            "The term 'copyleft' was popularized by Richard Stallman to describe open licensing.",
            "The GNU project, started in 1983, is one of the earliest open-source initiatives.",
            "Linus Torvalds was only 21 when he created Linux.",
            "Open-source software often powers proprietary systems in the background.",
            "The Kubernetes container system was open-sourced by Google in 2014.",
            "Python, although not entirely open governance at the start, thrives thanks to open contribution.",
            "OpenSSL is used in most secure internet connections.",
            "The Blender 3D software became open source in 2002 after a crowdfunding campaign.",
            "LibreOffice is maintained by The Document Foundation, a non-profit.",
            "Open source has been called 'the DNA of the Internet'.",
            "GitHub is the largest host of open-source projects worldwide.",
            "Some governments mandate open-source usage in their administrations.",
            "Open source is often more secure because anyone can inspect the code.",
            "WordPress, which powers 40% of the web, is open source.",
            "PHP, a widely used scripting language, is open source.",
            "VLC Media Player is one of the most famous open-source apps.",
            "Audacity, a popular audio editor, is open source.",
            "The first version of Linux was just 10,000 lines of code.",
            "Android’s kernel is based on Linux.",
            "Raspberry Pi relies heavily on open-source software.",
            "The Tor Browser is open source.",
            "Signal Messenger is open source.",
            "Open source powers most of the world's AI frameworks, like TensorFlow and PyTorch.",
            "The GNU General Public License (GPL) is one of the most used open-source licenses.",
            "BSD licenses are among the most permissive open-source licenses.",
            "The term 'free software' and 'open source' describe slightly different philosophies.",
            "The Open Source Initiative (OSI) maintains the official definition of open source.",
            "Wikipedia is built on open-source software: MediaWiki.",
            "GIMP is an open-source alternative to Photoshop.",
            "Inkscape is an open-source alternative to Illustrator.",
            "OBS Studio is an open-source broadcasting software used by streamers worldwide.",
            "Open source thrives on community collaboration.",
            "Most programming languages today have open-source compilers or interpreters.",
            "OpenJDK is the open-source implementation of the Java platform.",
            "Many governments use Linux for security reasons.",
            "NASA uses open-source software in space missions.",
            "The White House website runs on open-source technology.",
            "China’s fastest supercomputers run on open-source Linux.",
            "The top 500 supercomputers all run Linux.",
            "Some open-source projects are funded entirely by donations.",
            "Crowdfunding has saved several open-source projects from dying.",
            "Many open-source maintainers work voluntarily in their free time.",
            "Some companies build billion-dollar businesses on top of open source.",
            "Red Hat became the first billion-dollar open-source company.",
            "Open-source contributors often come from all over the world.",
            "Hacktoberfest encourages contributions to open source every October.",
            "Apache Kafka is open source and powers many big data systems.",
            "Elasticsearch, used for search, is based on open source.",
            "Node.js is an open-source runtime for JavaScript.",
            "npm, the package manager for Node.js, hosts millions of open packages.",
            "Rust, a systems programming language, is developed as open source.",
            "Go (Golang) is an open-source language created by Google.",
            "Swift, Apple’s programming language, is also open source.",
            "Even Microsoft has become one of the largest contributors to open source.",
            "Microsoft open-sourced .NET in 2014.",
            "Visual Studio Code is open source at its core.",
            "SQLite, the world’s most used database, is public domain and open source.",
            "Docker was open-sourced in 2013.",
            "Open source is not just software — hardware projects exist too.",
            "Arduino is an open-source hardware platform.",
            "3D printers like RepRap are based on open source.",
            "Wikipedia contributors are volunteers, much like open-source developers.",
            "Krita is an open-source digital painting software.",
            "MuseScore is an open-source music notation program.",
            "Jitsi is an open-source video conferencing tool.",
            "Mattermost is an open-source alternative to Slack.",
            "Open-source licenses ensure long-term software freedom.",
            "Android forks exist thanks to its open-source nature.",
            "LineageOS is a popular open-source Android fork.",
            "PostgreSQL is considered one of the most advanced open-source databases.",
            "Open-source conferences are held worldwide every year.",
            "GitHub sponsors program helps fund open-source maintainers.",
            "Companies like Google, Facebook, and Amazon contribute heavily to open source.",
            "TensorFlow was open-sourced by Google in 2015.",
            "PyTorch was open-sourced by Facebook in 2016.",
            "OpenAI initially started as an open-source project.",
            "Linux is one of the most contributed-to projects ever.",
            "Debian is one of the oldest Linux distributions, first released in 1993.",
            "Ubuntu is based on Debian and is widely used by beginners.",
            "Fedora is sponsored by Red Hat.",
            "Arch Linux is famous for its DIY philosophy.",
            "Open source has inspired collaboration beyond software.",
            "The Open Source Seed Initiative applies open-source principles to agriculture.",
            "Wikipedia’s open collaboration model is inspired by open source.",
            "Some of the biggest tech companies rely on open-source databases.",
            "Git was created specifically to help manage the Linux kernel’s open-source development.",
            "Linus Torvalds also created Git, not just Linux.",
            "Open-source projects often outlive proprietary ones.",
            "Many closed-source software secretly uses open-source components."
              ]
            }
            """;

        public static async Task<string> GetRandomFact()
        {
            var root = JsonSerializer.Deserialize<FunFactRoot>(funFacts);

            if (root == null || root.IT_Fun_Facts == null || root.IT_Fun_Facts.Count == 0)
                return "No facts available.";

            Random _random = new Random();
            int index = _random.Next(root.IT_Fun_Facts.Count);
            return root.IT_Fun_Facts[index];
        }
    }
}
